#debug or release
RUN_MODE: "debug"


PAGE_SIZE: 10
JWT_SECRET: "23347$040412"


HTTP_PORT: 8000
READ_TIMEOUT: 60
WRITE_TIMEOUT: 60

MySQL:
  Blog:
    USER: "root"
    PASSWORD: ""
    HOST: "127.0.0.1:3306"
    NAME: "blog"
    TABLE_PREFIX: "blog_"
